# Generated by Django 5.2.10 on 2026-01-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('SUBSCRIBER', 'Subscriber')], default='SUBSCRIBER', max_length=20),
        ),
    ]
