# Generated by Django 5.2.10 on 2026-01-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_role',
            field=models.CharField(choices=[('AUTHOR', 'Author'), ('MANAGER 1', 'Manager 1'), ('MANAGER 2', 'Manager 2')], default='AUTHOR', max_length=20),
        ),
    ]
