# Generated by Django 5.2.10 on 2026-01-28 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_category_blog_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='status',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_role',
            field=models.CharField(choices=[('AUTHOR', 'Author'), ('MANAGER1', 'Manager 1'), ('MANAGER2', 'Manager 2')], max_length=20),
        ),
    ]
