# Generated by Django 5.2.10 on 2026-01-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_category_created_at_alter_blog_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_role',
        ),
    ]
